version: "3.9"
services:

  client-one:
    privileged: true
    build: 
      context: ./client
    networks:
      full_network:
        ipv4_address: ${priv_ip_client1}/24
    command: bash -c "while :; do :; done & kill -STOP $$! && wait $$!"
    environment:
      private_address: ${priv_ip_client1}
      gateway_address: ${priv_ip_fw1}
    cap_add: 
      - all

  firewall-one:
    privileged: true
    build: 
      context: ./firewall
    networks:
      full_network:
        ipv4_address: ${priv_ip_fw1}/24
      full_network:
        ipv4_address: ${pub_ip_fw1}/24
    command: bash -c "while :; do :; done & kill -STOP $$! && wait $$!"
    environment: 
      fwprivate_address: ${priv_ip_fw1}
      fwpublic_address: ${pub_ip_fw1}
    cap_add: 
      - all

   
  coturn:
    image: coturn/coturn
    networks:
      full_network:
        ipv4_address: ${pub_ip_coturn}/24
    
  test-website:
    image: nginxdemos/hello
    networks:
      full_network:
        ipv4_address: ${pub_ip_website}/24




  firewall-two:
    privileged: true
    build: 
      context: ./firewall
    networks:
      full_network:
        ipv4_address: ${priv_ip_fw2}/24
      full_network:
        ipv4_address: ${pub_ip_fw2}/24
    environment: 
      fwprivate_address: ${priv_ip_fw2}
      fwpublic_address: ${pub_ip_fw2}
    cap_add: 
      - all
    
  client-two:
    privileged: true
    build: 
      context: ./client
    networks:
      full_network:
        ipv4_address: ${priv_ip_client2}/24
    command: sh -c "while :; do :; done & kill -STOP $$! && wait $$!"
    environment:
      private_address: ${priv_ip_client2}
      gateway_address: ${priv_ip_fw2}
    cap_add: 
      - all


networks:
  full_network:
    ipam:
      driver: default
      config:
      - subnet: ${subnet_full_net}
     
