version: "3.9"
services:

  client-one:
    build: 
      context: ./client
    networks:
      client1:
        ipv4_address: ${priv_ip_client1}
    command: bash -c "while :; do :; done & kill -STOP $$! && wait $$!"
    environment:
      private_address: ${priv_ip_client1}
      gateway_address: ${priv_ip_fw1}
    cap_add: 
      - all

  firewall-one:
    build: 
      context: ./firewall
    networks:
      client1:
        ipv4_address: ${priv_ip_fw1}
      internet:
        ipv4_address: ${pub_ip_fw1}
    environment: 
      fwprivate_address: ${priv_ip_fw1}
      fwpublic_address: ${pub_ip_fw1}
    cap_add: 
      - all

   
  coturn:
    image: coturn/coturn
    networks:
      internet:
        ipv4_address: ${pub_ip_coturn}
    
  test-website:
    image: nginxdemos/hello
    networks:
      internet:
        ipv4_address: ${pub_ip_website}



  firewall-two:
    build: 
      context: ./firewall
    networks:
      client2:
        ipv4_address: ${priv_ip_fw2}
      internet:
        ipv4_address: ${pub_ip_fw2}
    environment: 
      fwprivate_address: ${priv_ip_fw2}
      fwpublic_address: ${pub_ip_fw2}
    cap_add: 
      - all
    
  client-two:
    build: 
      context: ./client
    networks:
      client2:
        ipv4_address: ${priv_ip_client2}
    command: sh -c "while :; do :; done & kill -STOP $$! && wait $$!"
    environment:
      private_address: ${priv_ip_client2}
      gateway_address: ${priv_ip_fw2}
    cap_add: 
      - all


networks:
  client1:
    ipam:
      driver: default
      config:
      - subnet: ${subnet_cli1}
        gateway: ${subnet_cli1_fakeIP}
    internal: true

  internet:
    ipam:
      driver: default
      config:
      - subnet: ${subnet_internet}
        gateway: ${subnet_internet_gw}

  client2:
    ipam:
      driver: default
      config:
      - subnet: ${subnet_cli2}
        gateway: ${subnet_cli2_fakeIP}
    internal: true
     
